### ISSUE TITLE
Choose cache directly in template

### ISSUE THREAD

**Issue by rtpm** [twidi/django-adv-cache-tag#2]
Hi,

Thanks for great templatetag.

Did you consider adding a cache backend paramter in {% cache %} templateg? 

For example:
{% cache products_cache val1 val2 etc.. %}

with products_cache defined in CACHHE {} settings.py

I also found an example with adding "foo" parameter not working. (missing 'Node')

I am trying to get a 'fragment_name' resolvable but can't get this working.

Can you please include example of the way this can be done?

**Comment by twidi** [comment]
For the choice of the backend in the templatetag, I think I can do it as it's now possible it django, so If I do it, I'll respect their syntax (`using=products_cache`)

About the `foo` example, it's now corrected in `develop` (not released yet).

And for the resolve of `fragment_name`, I can check I think

**Comment by twidi** [comment]
For the fragment name, done in  #19 (not released, though)

**Comment by twidi** [comment]
For the choice of the fragment name in the template tag it's done in #21 (still not released)

**Comment by twidi** [comment]
Released !

Version **[0.2.1](https://pypi.python.org/pypi/django-adv-cache-tag/0.2.1)** for python **2** (**_only_**), and **[1.0.0](https://pypi.python.org/pypi/django-adv-cache-tag/1.0.0)** for python **3** (**_only_**).

Thanks again.
