### ISSUE TITLE
cache timeout of 0

### ISSUE THREAD

**Issue by oppianmatt** [twidi/django-adv-cache-tag#5]
docs say to use a cache timeout of 0 to cache forever, but that doesn't work in practice (django 1.6)

Using expire time of 0 means it expires straight away. Django docs say to use None to not expire but the code in adv-cache throws an error when doing so.

Here is the code in adv-cache, it shows it only accepts integers (None doesn't work):

    def get_expire_time(self):
        """
        Return the expire time passed to the templatetag.
        Must be an integer.
        """
        try:
            expire_time = self.node.expire_time.resolve(self.context)
        except template.VariableDoesNotExist:
            raise template.TemplateSyntaxError('"%s" tag got an unknown variable: %r' % (self.node.nodename, self.node.expire_time.var))
        try:
            expire_time = int(expire_time)
        except (ValueError, TypeError):
            raise template.TemplateSyntaxError('"%s" tag got a non-integer timeout value: %r' % (self.node.nodename, expire_time))

        return expire_time

Then in django/core/cache/backends/memcached.py (you can see if 0 is passed in it gets changed to -1 to expire immediately):

    def _get_memcache_timeout(self, timeout=DEFAULT_TIMEOUT):
        """
        Memcached deals with long (> 30 days) timeouts in a special
        way. Call this function to obtain a safe value for your timeout.
        """
        if timeout == DEFAULT_TIMEOUT:
            return self.default_timeout

        if timeout is None:
            # Using 0 in memcache sets a non-expiring timeout.
            return 0
        elif int(timeout) == 0:
            # Other cache backends treat 0 as set-and-expire. To achieve this
            # in memcache backends, a negative timeout must be passed.
            timeout = -1

        if timeout > 2592000: # 60*60*24*30, 30 days
            # See http://code.google.com/p/memcached/wiki/FAQ
            # "You can set expire times up to 30 days in the future. After that
            # memcached interprets it as a date, and will expire the item after
            # said date. This is a simple (but obscure) mechanic."
            #
            # This means that we have to switch to absolute timestamps.
            timeout += int(time.time())
        return int(timeout)

**Comment by twidi** [comment]
Yes you're right. I used a `redis` cache backend when I coded this library and `0` was for `no expire time`.
As I cannot be sure for all existing backend (and it's why I don't enforce this value), the only thing I can do is to update the documentation.
Thanks for having mentioned it.

**Comment by twidi** [comment]
Released ! It's in the doc.

Version **[0.2.1](https://pypi.python.org/pypi/django-adv-cache-tag/0.2.1)** for python **2** (**_only_**), and **[1.0.0](https://pypi.python.org/pypi/django-adv-cache-tag/1.0.0)** for python **3** (**_only_**).

Thanks again.
