### ISSUE TITLE
nocache and custom template filters.

### ISSUE THREAD

**Issue by mikecodona** [twidi/django-adv-cache-tag#6]
Apologies if there is something I've missed here.

When using nocache to prevent caching of some blocks I've noticed that custom libraries don't seem to be loaded. The CacheTag.render_nocache() method then tries to render the template and with the cached content within raw tags. This causes it to throw an exception when it encounters a filter which it doesn't have loaded within the {% nocache %} block.

I guess ideally it would inherit the loaded libraries of the template from the template containing the {% nocache %} block, though I haven't looked into how feasible this would be.

**Comment by twidi** [comment]
Sorry for being SO late on this.

The thing I should do is get the libraries loaded in the template and import them in the `nocache` part.
I don't know if I can do this, but I'll give it a try.

**Comment by twidi** [comment]
Note that a solution I currently use is to (re)load the libraries in the `nocache` block.

**Comment by mikecodona** [comment]
Thanks @twidi, yeah it would be really neat if it could pull them in automatically, but we currently use the same work around.

**Comment by twidi** [comment]
Done in #22  (But not released in PyPI for now)

I only did a simple test for this, if you want to test it more, feel free.

**Comment by twidi** [comment]
Released !

Version **[0.2.1](https://pypi.python.org/pypi/django-adv-cache-tag/0.2.1)** for python **2** (**_only_**), and **[1.0.0](https://pypi.python.org/pypi/django-adv-cache-tag/1.0.0)** for python **3** (**_only_**).

Thanks again.
